# Generated by Django 4.0 on 2021-12-20 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_topic_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 2, 3, 38, 898968)),
        ),
    ]
