# Generated by Django 4.0 on 2022-01-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_alter_entry_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
