# Generated by Django 4.0 on 2022-01-11 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_alter_entry_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
